apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: products

bases:
- ../../base

resources:
- products-ns.yaml
- netpol-only-same-ns.yaml
- netpol-allow-ingress.yaml
- netpol-allow-monitoring.yaml

