apiVersion: v1
kind: Service
metadata:
  name: ratings
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: ratings
    service: ratings
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: ratings