apiVersion: v1
kind: Service
metadata:
  name: reviews
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    app: reviews
    service: reviews
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: reviews