apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
spec:
  hard:
    pods: 10
    requests.cpu: 4000m
    requests.memory: 4Gi
    resourcequotas: 1
    requests.storage: 50Gi
    persistentvolumeclaims: 5
